name: Lint Markdown

on:
  push:
    paths:
      - '**.md'
      - '.markdownlint.json'
      - 'package.json'
      - '.github/workflows/**'
  pull_request:
    branches:
      - master
    paths:
      - '**.md'
      - '.markdownlint.json'
      - 'package.json'
      - '.github/workflows/**'

jobs:
  # [original source of job "prepare"](https://github.com/srz-zumix/ci-skip/blob/master/.github/workflows/main.yml#L15)
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: 'Print GITHUB_EVENT_PATH'
        run: cat ${GITHUB_EVENT_PATH}

      - name: Check [ci skip] or [skip ci]
        # skip commits with [ci skip] or [skip ci], except on an action triggered by push of a version tag
        if: "( contains(github.event.head_commit.message, '[ci skip]') || contains(github.event.head_commit.message, '[skip ci]') ) && !startsWith(github.ref, 'refs/tags/v1.')"
        run: |
          # 78 is conventional "neutral exit code"
          exit 78
  lint:
    needs: prepare
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Read .nvmrc
        id: nvmrc
        run: echo "::set-output name=nvmrc::$(cat .nvmrc)"

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvmrc.outputs.nvmrc }}

      - name: Get yarn cache
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --silent --frozen-lockfile
        env:
          CI: true

      - name: Lint Markdown
        run: yarn markdownlint .

      - name: Lint javascript in markdown
        run: yarn eslint --ext md .
